export const HEADING_LIST_REQUEST = 'HEADING_LIST_REQUEST'
export const HEADING_LIST_SUCCESS = 'HEADING_LIST_SUCCESS'
export const HEADING_LIST_FAIL = 'HEADING_LIST_FAIL'

export const HEADING_CREATE_REQUEST = 'HEADING_CREATE_REQUEST'
export const HEADING_CREATE_SUCCESS = 'HEADING_CREATE_SUCCESS'
export const HEADING_CREATE_FAIL = 'HEADING_CREATE_FAIL'