export const TICKET_LIST_REQUEST = 'TICKET_LIST_REQUEST'
export const TICKET_LIST_SUCCESS = 'TICKET_LIST_SUCCESS'
export const TICKET_LIST_FAIL = 'TICKET_LIST_FAIL'


export const TICKET_CREATE_REQUEST = 'TICKET_CREATE_REQUEST'
export const TICKET_CREATE_SUCCESS = 'TICKET_CREATE_SUCCESS'
export const TICKET_CREATE_FAIL = 'TICKET_CREATE_FAIL'
export const TICKET_CREATE_RESET = 'TICKET_CREATE_RESET'


export const TICKET_DELETE_REQUEST = 'TICKET_DELETE_REQUEST'
export const TICKET_DELETE_SUCCESS = 'TICKET_DELETE_SUCCESS'
export const TICKET_DELETE_FAIL = 'TICKET_DELETE_FAIL'


export const TICKET_CREATE_HEADING_REQUEST = 'TICKET_CREATE_HEADING_REQUEST'
export const TICKET_CREATE_HEADING_SUCCESS = 'TICKET_CREATE_HEADING_SUCCESS'
export const TICKET_CREATE_HEADING_FAIL = 'TICKET_CREATE_HEADING_FAIL'
export const TICKET_CREATE_HEADING_RESET = 'TICKET_CREATE_HEADING_RESET'

export const TICKET_DELETE_HEADING_REQUEST = 'TICKET_DELETE_HEADING_REQUEST'
export const TICKET_DELETE_HEADING_SUCCESS = 'TICKET_DELETE_HEADING_SUCCESS'
export const TICKET_DELETE_HEADING_FAIL = 'TICKET_DELETE_HEADING_FAIL'
export const TICKET_DELETE_HEADING_RESET = 'TICKET_DELETE_HEADING_RESET'

export const TICKET_UPDATE_REQUEST = 'TICKET_UPDATE_REQUEST'
export const TICKET_UPDATE_SUCCESS = 'TICKET_UPDATE_SUCCESS'
export const TICKET_UPDATE_FAIL = 'TICKET_UPDATE_FAIL'
export const TICKET_UPDATE_RESET = 'TICKET_UPDATE_RESET'


export const TICKET_BODY_UPDATE_REQUEST = 'TICKET_UPDATE_REQUEST'
export const TICKET_BODY_UPDATE_SUCCESS = 'TICKET_UPDATE_SUCCESS'
export const TICKET_BODY_UPDATE_FAIL = 'TICKET_UPDATE_FAIL'


export const TICKET_CREATE_HEADING2_REQUEST = 'TICKET_CREATE_HEADING2_REQUEST'
export const TICKET_CREATE_HEADING2_SUCCESS = 'TICKET_CREATE_HEADING2_SUCCESS'
export const TICKET_CREATE_HEADING2_FAIL = 'TICKET_CREATE_HEADING2_FAIL'
export const TICKET_CREATE_HEADING2_RESET = 'TICKET_CREATE_HEADING2_RESET'


export const TICKET_DELETE_HEADING2_REQUEST = 'TICKET_DELETE_HEADING2_REQUEST'
export const TICKET_DELETE_HEADING2_SUCCESS = 'TICKET_DELETE_HEADING2_SUCCESS'
export const TICKET_DELETE_HEADING2_FAIL = 'TICKET_DELETE_HEADING2_FAIL'
export const TICKET_DELETE_HEADING2_RESET = 'TICKET_DELETE_HEADING2_RESET'

export const TICKET_DUPLICATE_REQUEST = 'TICKET_DUPLICATE_REQUEST'
export const TICKET_DUPLICATE_SUCCESS = 'TICKET_DUPLICATE_SUCCESS'
export const TICKET_DUPLICATE_FAIL = 'TICKET_DUPLICATE_FAIL'
export const TICKET_DUPLICATE_RESET = 'TICKET_DUPLICATE_RESET'

