export const TICKET_LIST_REQUEST = 'TICKET_LIST_REQUEST'
export const TICKET_LIST_SUCCESS = 'TICKET_LIST_SUCCESS'
export const TICKET_LIST_FAIL = 'TICKET_LIST_FAIL'


export const TICKET_CREATE_REQUEST = 'TICKET_CREATE_REQUEST'
export const TICKET_CREATE_SUCCESS = 'TICKET_CREATE_SUCCESS'
export const TICKET_CREATE_FAIL = 'TICKET_CREATE_FAIL'
export const TICKET_CREATE_RESET = 'TICKET_CREATE_RESET'


export const TICKET_DELETE_REQUEST = 'TICKET_DELETE_REQUEST'
export const TICKET_DELETE_SUCCESS = 'TICKET_DELETE_SUCCESS'
export const TICKET_DELETE_FAIL = 'TICKET_DELETE_FAIL'
