import axios from "axios";
import {
  HEADING_LIST_REQUEST,
  HEADING_LIST_SUCCESS,
  HEADING_LIST_FAIL,
  HEADING_CREATE_REQUEST,
  HEADING_CREATE_SUCCESS,
  HEADING_CREATE_FAIL,
  HEADING_CREATE_RESET,

  HEADING_DELETE_REQUEST,
  HEADING_DELETE_SUCCESS,
  HEADING_DELETE_FAIL,

  
} from "../constants/headingConstants";